# Markov Text Generator
#
#
import random
#Function 1
def create_dictionary(filename):
    """takes a string representing the name of a text file, and that returns a dictionary of key-value pairs
    """
    file = open(filename,'r')
    text = file.read()
    file.close()

    words = text.split()
    d = {}
    current_word = '$'
    
    for next_word in words:
        if current_word not in d:
            d[current_word] = [next_word]
        else:
            d[current_word] += [next_word]
        if next_word[-1] in '.!?':
            current_word = '$'
        else:
            current_word = next_word
    return d

#Function 2
def generate_text(word_dict, num_words):
    """takes as parameters a dictionary of word transitions (generated by the create_dictionary function) named word_dict and a positive integer named num_words. 
    """
    current_word = '$'

    s = ''

    while num_words >0:
        next_word = random.choice(word_dict[current_word])
        s += next_word
        num_words -= 1
        if num_words > 0: 
            s += ' '
        if next_word[-1] in '.!?':
            current_word = '$'
        else:
            current_word = next_word
    print(s)
